version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - PIZZERIA_PHONE_NUMBER=${PIZZERIA_PHONE_NUMBER}
      - PYTHONPATH=/app
    volumes:
      - .:/app
